# -*- coding: utf-8 -*-
"""Computational Comparison of Biofuel Molecular Properties

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKV-Hvij3BRjyuvBJHHHs3kTSHSBwnER

# Computational Comparison of 6 Biofuels' Molecular Properties

Author: Matthew Deng

This notebook uses code initially generated with the assistance from Claude AI's Python capablities and revised via human editing to interpret data and visually display relationships between various molecular properties among 6 biofuels.
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("fuel_molecules.csv")
print(df)

plt.scatter(df["Carbons"], df["BoilingPoint"])
plt.xlabel("Carbon Atoms")
plt.ylabel("Boiling Point (°C)")
plt.title("Carbon Atoms vs. Boiling Point")

# Errors arose whilst attempting to create the graphs. Fixed the for loop to create the graphs.
for i, name in enumerate(df["Molecule"]):
    plt.annotate(name, (df["Carbons"][i], df["BoilingPoint"][i]))
plt.show()

plt.scatter(df["MolecularWeight"], df["BoilingPoint"])
plt.xlabel("Molecular Weight (g/mol)")
plt.ylabel("Boiling Point (°C)")
plt.title("Molecular Weight vs. Boiling Point")

# Errors arose whilst attempting to create the graphs. Fixed the for loop to create the graphs.
for i, name in enumerate(df["Molecule"]):
    plt.annotate(name, (df["MolecularWeight"][i], df["BoilingPoint"][i]))
plt.show()

pairs = ["Ethane", "Ethanol", "Butane", "Butanol"]
subset = df[df["Molecule"].isin(pairs)]

colors = ["orange" if ox == 1 else "blue" for ox in subset["Oxygen"]]
plt.bar(subset["Molecule"], subset["BoilingPoint"], color=colors)
plt.xlabel("Molecule")
plt.ylabel("Boiling Point (°C)")
plt.title("Hydrocarbon vs. Alcohol Boiling Points")
plt.show()