# -*- coding: utf-8 -*-
"""Computational Comparison of 20 Organic Compounds' Molecular Properties

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvS1bSuaLKyPFacPRtqrjQ-HqnzkHbPa

# Computational Comparison of 20 Organic Compounds' Molecular Properties

Author: Matthew Deng

This notebook uses code initially generated with the asisstance from Claude AI's Python capablities and revised via human editing to interpret data and visually display relationships between various molecular properties among 20 organic compounds.

# Scatterplots
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("20_fuel_properties_dataset.csv")

df = df.replace("−", "-", regex=True)

numeric_cols = [
    "Carbon", "Hydrogen", "Oxygen", "Weight (g/mol)", "Boiling Point (°C)",
    "Carbon Chain Length", "Avg C-C (Å)", "Avg C-H (Å)", "Avg C-O (Å)",
    "Avg O-H (Å)", "Avg C=O (Å)", "Bond Angle (°)", "Rotatable Bonds"
]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Has Oxygen"] = df["Has Oxygen"].map({0: "No", 1: "Yes"})
df["Polar"] = df["Polar"].map({0: "No", 1: "Yes"})
df["Hydrogen Bonding"] = df["Hydrogen Bonding"].map({0: "No", 1: "Yes"})

print(df.dtypes)
print(df)

clean = df[["Carbon Chain Length", "Boiling Point (°C)"]].dropna()
x = clean["Carbon Chain Length"]
y = clean["Boiling Point (°C)"]

m, b = np.polyfit(x, y, 1)
r_squared = np.corrcoef(x, y)[0, 1] ** 2

plt.scatter(x, y, color="steelblue", edgecolor="black")
plt.plot(x, m * x + b, color="red")
plt.xlabel("Carbon Chain Length")
plt.ylabel("Boiling Point (°C)")
plt.title("Carbon Chain Length vs. Boiling Point")
plt.text(0.05, 0.95, f"y = {m:.2f}x + {b:.2f}\nR² = {r_squared:.3f}",
         transform=plt.gca().transAxes, va="top")
plt.grid(True)
plt.show()

clean = df[["Weight (g/mol)", "Boiling Point (°C)"]].dropna()
x = clean["Weight (g/mol)"]
y = clean["Boiling Point (°C)"]

m, b = np.polyfit(x, y, 1)
r_squared = np.corrcoef(x, y)[0, 1] ** 2

plt.scatter(x, y, color="steelblue", edgecolor="black")
plt.plot(x, m * x + b, color="red")
plt.xlabel("Molecular Weight (g/mol)")
plt.ylabel("Boiling Point (°C)")
plt.title("Molecular Weight vs. Boiling Point")
plt.text(0.05, 0.95, f"y = {m:.2f}x + {b:.2f}\nR² = {r_squared:.3f}",
         transform=plt.gca().transAxes, va="top")
plt.grid(True)
plt.show()

clean = df[["Rotatable Bonds", "Boiling Point (°C)"]].dropna()
x = clean["Rotatable Bonds"]
y = clean["Boiling Point (°C)"]

m, b = np.polyfit(x, y, 1)
r_squared = np.corrcoef(x, y)[0, 1] ** 2

plt.scatter(x, y, color="steelblue", edgecolor="black")
plt.plot(x, m * x + b, color="red")
plt.xlabel("Rotatable Bonds")
plt.ylabel("Boiling Point (°C)")
plt.title("Rotatable Bonds vs. Boiling Point")
plt.text(0.05, 0.95, f"y = {m:.2f}x + {b:.2f}\nR² = {r_squared:.3f}",
         transform=plt.gca().transAxes, va="top")
plt.grid(True)
plt.show()

"""# Boxplots

"""

clean = df[["Family", "Boiling Point (°C)"]].dropna()
groups = clean.groupby("Family")["Boiling Point (°C)"].apply(list)

plt.boxplot(groups.values, labels=groups.index, patch_artist=True)
plt.xlabel("Family")
plt.ylabel("Boiling Point (°C)")
plt.title("Boiling Point vs. Family")
plt.xticks(rotation=30, ha="right")
plt.grid(True)
plt.tight_layout()
plt.show()

clean = df[["Polar", "Boiling Point (°C)"]].dropna()
groups = clean.groupby("Polar")["Boiling Point (°C)"].apply(list)

plt.boxplot(groups.values, labels=groups.index, patch_artist=True)
plt.xlabel("Polar")
plt.ylabel("Boiling Point (°C)")
plt.title("Boiling Point vs. Polarity")
plt.grid(True)
plt.show()

clean = df[["Hydrogen Bonding", "Boiling Point (°C)"]].dropna()
groups = clean.groupby("Hydrogen Bonding")["Boiling Point (°C)"].apply(list)

plt.boxplot(groups.values, labels=groups.index, patch_artist=True)
plt.xlabel("Hydrogen Bonding")
plt.ylabel("Boiling Point (°C)")
plt.title("Boiling Point vs. Hydrogen Bonding")
plt.grid(True)
plt.show()

clean = df[["Has Oxygen", "Boiling Point (°C)"]].dropna()
groups = clean.groupby("Has Oxygen")["Boiling Point (°C)"].apply(list)

plt.boxplot(groups.values, labels=groups.index, patch_artist=True)
plt.xlabel("Has Oxygen")
plt.ylabel("Boiling Point (°C)")
plt.title("Boiling Point vs. Oxygen Presence")
plt.grid(True)
plt.show()

"""# Bar Charts"""

avg = df.groupby("Family")["Boiling Point (°C)"].mean()

colors = ["darkorange" if v < 0 else "steelblue" for v in avg.values]

plt.bar(avg.index, avg.values, color=colors)
for i, v in enumerate(avg.values):
    plt.text(i, v, f"{v:.1f}", ha="center", va="bottom")
plt.xlabel("Family")
plt.ylabel("Average Boiling Point (°C)")
plt.title("Average Boiling Point vs. Family")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

"""# Correlation Analysis"""

numeric_df = df.select_dtypes(include="number").copy()

numeric_df["Has Oxygen"] = df["Has Oxygen"].map({"No": 0, "Yes": 1})
numeric_df["Polar"] = df["Polar"].map({"No": 0, "Yes": 1})
numeric_df["Hydrogen Bonding"] = df["Hydrogen Bonding"].map({"No": 0, "Yes": 1})

corr = numeric_df.corr()
print(corr)

plt.figure(figsize=(9, 8))
plt.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.colorbar(label="Correlation Coefficient")
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

print(corr["Boiling Point (°C)"].sort_values(ascending=False))

"""# Statistics Summary"""

cols = ["Weight (g/mol)", "Boiling Point (°C)", "Carbon Chain Length", "Bond Angle (°)", "Rotatable Bonds"]

summary = pd.DataFrame({
    "Mean": df[cols].mean(),
    "Median": df[cols].median(),
    "Std Dev": df[cols].std(),
    "Min": df[cols].min(),
    "Max": df[cols].max(),
    "Range": df[cols].max() - df[cols].min()
})

print(summary)