# -*- coding: utf-8 -*-
"""Machine Learning Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ysnuV7wA1qketL2gD3hGCgyZJLiHhcy

# Machine Learning Prediction of Fuel Properties

Author: Matthew Deng

This notebook uses Python and machine learning to predict the boiling points of 100 organic compounds based on molecular properties. Four regression models are compared, and the best performing model is analyzed using feature importance and prediction accuracy.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error
)

uploaded = files.upload()

original_df = pd.read_csv("fuel_ml_dataset.csv")

print(original_df.head())

print(original_df.shape)

df = original_df.copy()

df = df.replace("−", "-", regex=True)

df["Boiling Point (°C)"] = pd.to_numeric(
    df["Boiling Point (°C)"],
    errors="coerce"
)

df = df.dropna(subset=["Boiling Point (°C)"])

cols_to_drop = [
    "Molecule",
    "Formula",
    "Functional Group"
]

df = df.drop(columns=cols_to_drop)

df = pd.get_dummies(
    df,
    columns=["Family"]
)

print(df.head())

X = df.drop(columns=["Boiling Point (°C)"])

y = df["Boiling Point (°C)"]

print(X.columns)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

"""# Evaluation Function"""

def evaluate_model(name, model):

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    r2 = r2_score(y_test, predictions)

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            predictions
        )
    )

    mae = mean_absolute_error(
        y_test,
        predictions
    )

    print(f"\n{name}")
    print(f"R² = {r2:.4f}")
    print(f"RMSE = {rmse:.4f}")
    print(f"MAE = {mae:.4f}")

    return model, predictions, r2, rmse, mae

"""# Model Training"""

lr_model, lr_pred, lr_r2, lr_rmse, lr_mae = evaluate_model(
    "Linear Regression",
    LinearRegression()
)

dt_model, dt_pred, dt_r2, dt_rmse, dt_mae = evaluate_model(
    "Decision Tree",
    DecisionTreeRegressor(random_state=42)
)

rf_model, rf_pred, rf_r2, rf_rmse, rf_mae = evaluate_model(
    "Random Forest",
    RandomForestRegressor(random_state=42)
)

gb_model, gb_pred, gb_r2, gb_rmse, gb_mae = evaluate_model(
    "Gradient Boosting",
    GradientBoostingRegressor(random_state=42)
)

"""# Model Performance Comparison"""

results = pd.DataFrame({

    "Model":[
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],

    "R²":[
        lr_r2,
        dt_r2,
        rf_r2,
        gb_r2
    ],

    "RMSE":[
        lr_rmse,
        dt_rmse,
        rf_rmse,
        gb_rmse
    ],

    "MAE":[
        lr_mae,
        dt_mae,
        rf_mae,
        gb_mae
    ]

})

results

"""# Random Forest Feature Importance Analysis"""

feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feature_importance

"""# Feature Importance Graph"""

plt.figure(figsize=(8,7))

feature_importance.sort_values().plot(
    kind="barh",
    color="steelblue",
    edgecolor="black"
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Random Forest Feature Importance")

plt.tight_layout()

plt.show()

"""# Random Forest Feature Importance Table"""

feature_importance_df = (
    feature_importance
    .rename("Importance")
    .reset_index()
)

feature_importance_df.columns = [
    "Feature",
    "Importance"
]

feature_importance_df

"""# Predictions"""

best_predictions = gb_model.predict(X_test)

predictions_df = pd.DataFrame({

    "Molecule":
    original_df.loc[X_test.index, "Molecule"].values,

    "Actual":
    y_test.values,

    "Predicted":
    best_predictions

})

predictions_df["Error"] = (
    predictions_df["Actual"]
    -
    predictions_df["Predicted"]
).abs()

predictions_df = predictions_df.sort_values(
    "Error"
)

predictions_df

"""# Actual vs. Predicted Plot"""

plt.figure(figsize=(7,7))

plt.scatter(
    y_test,
    best_predictions,
    edgecolor="black"
)

lims = [
    min(y_test.min(), best_predictions.min()),
    max(y_test.max(), best_predictions.max())
]

plt.plot(
    lims,
    lims,
    "r"
)

plt.xlabel("Actual")
plt.ylabel("Predicted")

plt.title("Actual vs. Predicted Boiling Point")

plt.tight_layout()

plt.show()

"""# Residual Plot"""

residuals = y_test - best_predictions

plt.figure(figsize=(7,6))

plt.scatter(
    best_predictions,
    residuals,
    edgecolor="black"
)

plt.axhline(
    0,
    linestyle="--",
    color="red"
)

plt.xlabel("Predicted")
plt.ylabel("Residual")

plt.title("Residual Plot")

plt.tight_layout()

plt.show()